config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :actors
  resources :movies

  root 'welcome#index'
end

app/models/actor.rb
# == Schema Information
#
# Table name: actors
#
#  id            :integer          not null, primary key
#  name          :string
#  date_of_birth :date
#  description   :text
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Actor < ApplicationRecord
  has_and_belongs_to_many :movies
  #has_and_belongs_to_many :casts, :join_table => "casts", :class_name => "Movie"
  validates :name, presence: true, format: { with: /\A[a-zA-Z ]+\z/, message: ' : Invalid format' }
  validates :date_of_birth, presence: true 
  validates :description, presence: true, length: { in: 5..500 }
  validate :validate_date_of_birth 

  def self.search(search)
    where("name LIKE ?", "%#{search}%")
  end

  def validate_date_of_birth
    errors.add("data_of_birth", "Date from future not allowed") if date_of_birth &&  date_of_birth > Time.now
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
# == Schema Information
#
# Table name: movies
#
#  id           :integer          not null, primary key
#  name         :string
#  description  :string
#  rating       :integer
#  release_date :date
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Movie < ApplicationRecord

  has_and_belongs_to_many :actors
  #has_and_belongs_to_many :casts, :join_table => "casts", :class_name => "Actor"
  validates :name, :release_date, :description, :rating, presence: { message: ' : Field cannot be empty'}
  validates :description, length: { in: 6...500 }
  validates_inclusion_of :rating, {:in => 0..5, message: ' : Rating must be between 0 to 5'}

  def self.search(search)
    where("name LIKE ?", "%#{search}%")
  end
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
  def index
    @actors = Actor.all
    if params[:search]
      @actors = Actor.search(params[:search]).order("created_at DESC")
    else
      @actors = Actor.all.order('created_at DESC')
    end
    respond_to do |format|
      format.html
      format.json  { render :json => @movies }
    end
  end

  def show
    @movies = Movie.all
    @actor = Actor.find(params[:id])
  end

  def new
    @actor = Actor.new
  end

  def edit
    @actor = Actor.find(params[:id])
  end

  def create
    @actor = Actor.new(actor_params)
    if @actor.save
      redirect_to @actor
    else
      render 'new'
    end
  end

  def update
    @actor = Actor.find(params[:id])
    @movies = Movie.all
    if(params[:movie_id])
      @actor.movies << @movies.find_by(id: params[:movie_id])
      redirect_to @actor
    else
      if @actor.update(actor_params)
        redirect_to @actor
      else
        render 'edit'
      end
    end
  end

  def destroy
    @actor = Actor.find(params[:id])
    @actor.destroy
    redirect_to actors_path
  end

  private
  def actor_params
    params.require(:actor).permit(:name, :date_of_birth, :description)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def new
    @movie = Movie.new
    Movie.search(params[:id])
  end

  def create
    @movie = Movie.new(movie_params)
    if @movie.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def index
    @movies = Movie.all

    if params[:search]
      @movies = Movie.search(params[:search]).order("created_at DESC")
    else
      @movies = Movie.all.order('created_at DESC')
    end
    respond_to do |format|
      format.html
      format.json  { render :json => @movies }
    end
  end

  def show
    @movie = Movie.find(params[:id])
    @actors = Actor.all
    respond_to do |format|
      format.html
      format.json  { render :json => @movie }
    end
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def update
    @movie = Movie.find(params[:id])
    @actors = Actor.all
    #for adding actor to the movie
    if(params[:actor_id])
      @movie.actors << Actor.find(params[:actor_id])
      redirect_to @movie
    #for updating the actor
    else
      if @movie.update(movie_params)
        redirect_to @movie
      else
        render 'edit'
      end
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to root_path
  end

  private
  
  def movie_params
    params.require(:movie).permit(:name, :description, :rating, :release_date)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @movie_results = Movie.search(params[:search_term])
    @actor_results = Actor.search(params[:search_term])
  end
end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/actors/_form.haml
= form_with model: @actor, local: true do |form|
  - if @actor.errors.any?
    #error_explanation
      %h2
        = pluralize(@actor.errors.count, "Error")
        prohibited this movie from being saved:
      %ul
        - @actor.errors.full_messages.each do |msg|
          %li= msg

  %table.table.table-dark
    %tr
      %td
        = form.label :name
      %td
        = form.text_field :name
    %tr
      %td
        = form.label :description
      %td
        = form.text_area :description
    %tr
      %td
        = form.label :date_of_birth
      %td
        = form.date_field :date_of_birth
    %tr
      %td
        = form.submit :class => "btn btn-success"

app/views/actors/edit.haml
.container
  .jumbotron
    %h4.card-title Edit Actor: (#{link_to @actor.name, movie_path(@actor)})
    = render 'form'

app/views/actors/index.haml
.container
  .jumbotron
    %h1 All actors:
    = link_to "Add new actor", new_actor_path, class: 'btn btn-success'
    %br
    %br
    %h3 Search Actor
    = form_for(actors_path, :method => "get", id: "search-form") do
      = text_field_tag :search, params[:search], placeholder: "Search Actor"
      = submit_tag "Search", name: nil
    - unless @actors.present?
      .alert.alert-warning
        There are no actors matching '#{params[:search]}'
    - else
      %table.table.table-blue
        %th Name
        %th Number of movies
        - @actors.each do |actor|
          %tr
            %td= link_to(actor.name, actor_path(actor))
            %td= actor.movies.length
            %td= link_to 'Delete', actor_path(actor),  |
                method: :delete,                    |
                data: { confirm: 'Are you sure?' }, |
                class: "btn btn-danger"             |
            %td= link_to 'Edit', edit_actor_path(actor), class: 'btn btn-warning'

app/views/actors/new.haml
.container
  .jumbotron
    .container
      %h4.card-title Add actor
      = render 'form'

app/views/actors/show.haml
.container
  %br
  .jumbotron
    .row
      .col
        %h1= @actor.name
        .btn-group
          %p= link_to 'Delete', actor_path(@actor), |
              method: :delete,                    |
              data: { confirm: 'Are you sure?' }, |
              class: 'btn btn-danger',            |
              style: 'margin-right: 20px'
          %p= link_to 'Edit', edit_actor_path(@actor), class: 'btn btn-warning'
        .card
          .card-body
            %p
              %b> Description
              \: #{@actor.description}
      .col
        %h4 Movies
        = form_for @actor do |form|
          %p
            %select{ :name => "movie_id" }
              - @movies.each do |movie|
                - unless(@actor.movies.include?(movie))
                  %option{:value => movie.id}= movie.name
            =form.submit "Add Movie", :class => "btn btn-success"

        %table.table
          - @actor.movies.each do |movie|
            %tr
              %td.card= link_to movie['name'], movie_path(movie)

app/views/layouts/application.haml
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title IMDB
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .container
      .btn-group
        - if current_page?(root_path)
          = link_to 'Home', root_path, class: 'btn btn-primary active'
        - else
          = link_to 'Home', root_path, class: 'btn btn-primary'

        - if current_page?(movies_path)
          = link_to 'Movies', movies_path, class: 'btn btn-primary active'
        - else
          = link_to 'Movies', movies_path, class: 'btn btn-primary'

        - if current_page?(actors_path)
          = link_to 'Actors', actors_path, class: 'btn btn-primary active'
        - else
          = link_to 'Actors', actors_path, class: 'btn btn-primary'
    = yield

app/views/movies/_form.haml
= form_with model: @movie, local: true do |form|
  - if @movie.errors.any?
    #error_explanation
      %h2
        = pluralize(@movie.errors.count, "error")
        prohibited
        this movie from being saved:
      %ul
        - @movie.errors.full_messages.each do |msg|
          %li= msg
  %table.table.table-dark
    %tr
      %td
        = form.label :name
      %td
        = form.text_field :name
    %tr
      %td
        = form.label :description
      %td
        = form.text_area :description
    %tr
      %td
        = form.label :release_date
      %td
        = form.date_field :release_date
    %tr
      %td
        = form.label :rating
      %td
        = form.number_field :rating
    %tr
      %td
        = form.submit :class => "btn btn-success"

app/views/movies/edit.haml
.container
  .jumbotron
    %h4.card-title
      Edit Movie (#{link_to @movie.name, movie_path(@movie)})
    = render 'form'

app/views/movies/index.haml
.container
  .jumbotron
    %h1 All movies:
    = link_to "Add new movie", new_movie_path, class: 'btn btn-success'
    %br
    %br
    %h3 Search Movie
    = form_for(movies_path, :method => "get", id: "search-form") do
      = text_field_tag :search, params[:search], placeholder: "Search Movies"
      = submit_tag "Search", name: nil
    - unless @movies.present?
      .alert.alert-warning
        There are no movies matching '#{params[:search]}'
    - else
      %table.table.table-blue
        %th Name
        %th Rating
        %th #Actors
        %th Release Date
        - @movies.each do |movie|
          %tr
            %td= link_to(movie.name, movie_path(movie))
            %td= movie.rating
            %td= movie.actors.length
            %td= movie.release_date
            %td= link_to 'Delete', movie_path(movie),  |
                method: :delete,                    |
                data: { confirm: 'Are you sure?' }, |
                class: "btn btn-danger"             |
            %td= link_to 'Edit', edit_movie_path(movie), class: 'btn btn-warning'

app/views/movies/new.haml
.container
  .jumbotron
    .container
      %h4.card-title Add Movie
      = render 'form'

app/views/movies/show.haml
.container
  %br/
  .jumbotron
    .row
      .col
        %h1= @movie.name
        .btn-group
          %p= link_to 'Delete', movie_path(@movie), |
              method: :delete,                    |
              data: { confirm: 'Are you sure?' }, |
              class: 'btn btn-danger',            |
              style: 'margin-right: 20px'
          %p= link_to 'Edit', edit_movie_path(@movie), class: 'btn btn-warning'
        .card
          .card-body
            %p
              %b> Rating
              \: #{@movie.rating}
            %p
              %b> Release Date
              \: #{@movie.release_date}
            %p
              .container
              \ #{@movie.description}
      .col
        %h4 Actors
        = form_for @movie do |form|
          %p
            %select{ :name => "actor_id" }
              - @actors.each do |actor|
                - unless(@movie.actors.include?(actor))
                  %option{:value => actor.id}= actor.name
            =form.submit "Add Actor", :class => "btn btn-success"
        %table.table
          - @movie.actors.each do |actor|
            %tr
              %td.card= link_to actor['name'], actor_path(actor)

app/views/welcome/index.haml
.container
  .jumbotron
    %h1 IMDB
    = form_for('welcome#index', :method => "get", id: "search-form") do
      = text_field_tag :search_term, params[:search_term], placeholder: "Search"
      = submit_tag "Search", name: nil, class: 'btn btn-success'
    - if params[:search_term]
      %h3 Actors:
      - unless @actor_results.present?
        .alert.alert-warning
          There are no actors matching '#{params[:search_term]}'
      - else
        %table.table
          %th Name
          %th Number of movies
          - @actor_results.each do |actor|
            %tr
              %td= link_to(actor.name, actor_path(actor))
              %td= actor.movies.length
              %td= link_to 'Delete', actor_path(actor),  |
                  method: :delete,                    |
                  data: { confirm: 'Are you sure?' }, |
                  class: "btn btn-danger"             |
              %td= link_to 'Edit', edit_actor_path(actor), class: 'btn btn-warning'
      %hr
      %h3 Movies
      - unless @movie_results.present?
        .alert.alert-warning
          There are no movies matching '#{params[:search_term]}'
        %br
      - else
        %table.table
          %th Name
          %th Rating
          %th #Actors
          %th Release Date
          - @movie_results.each do |movie|
            %tr
              %td= link_to(movie.name, movie_path(movie))
              %td= movie.rating
              %td= movie.actors.length
              %td= movie.release_date
              %td= link_to 'Delete', movie_path(movie),  |
                  method: :delete,                    |
                  data: { confirm: 'Are you sure?' }, |
                  class: "btn btn-danger"             |
              %td= link_to 'Edit', edit_movie_path(movie), class: 'btn btn-warning'